### ISSUE TITLE
Question: what are the differences between undo and redo logs? 

### ISSUE THREAD

**Issue by simbo1905** [DarinM223/disk-utils#8]
Building the API docs and flipping between disk_utils::wal::undo_log::UndoLog and disk_utils::wal::redo_log::RedoLog they have the same API. What exactly are the differences between these two log implementations? Thanks!

**Comment by DarinM223** [comment]
That's a good question. Both undo logs and redo logs have the same API because they essentially do the same thing. The differences between the implementations are mostly performance tradeoffs.

Undo logs will force the backing data store to flush all changes to the disk before every commit (see https://github.com/DarinM223/disk-utils/blob/master/src/wal/undo_log.rs#L93). Redo logs instead will store the committed changes until the backing data store decides to flush them to disk (the changes are stored in the Changes struct https://github.com/DarinM223/disk-utils/blob/master/src/wal/redo_log.rs#L18).

So an undo log will commit slower than a redo log because all the changes have to be flushed first, but a redo log can run out of memory if the stored changes grow too much.
